# PyDev console: starting.
# Python 3.7.3 (default, Apr 22 2020, 13:29:22)
# [GCC 8.3.0] on linux
# tpl = (1,2)
# type(tpl)
# <class 'tuple'>
# dir(tpl)
# ['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']
# tuple(range(6))
# (0, 1, 2, 3, 4, 5)
# 2+3*4
# 14
# (2+3)*4
# 20
# (6)
# 6
# type((6))
# <class 'int'>
# (8,)
# (8,)
# type((8,))
# <class 'tuple'>
# [9,]
# [9]
# registro('Adriano', 47)
# Traceback (most recent call last):
#   File "<input>", line 1, in <module>
# NameError: name 'registro' is not defined
# registro=('Adriano', 47)
# nome, idade = registro
# nome
# 'Adriano'
# idade
# 47
# nome, idade, d = registro
# Traceback (most recent call last):
#   File "<input>", line 1, in <module>
# ValueError: not enough values to unpack (expected 3, got 2)
# nome, idade = (1,2,3)
# Traceback (most recent call last):
#   File "<input>", line 1, in <module>
# ValueError: too many values to unpack (expected 2)
# registro_2=('Ros창ngela', 39)
# registro + registro_2
# ('Adriano', 47, 'Ros창ngela', 39)
# registro
# ('Adriano', 47)
# registro_2
# ('Ros창ngela', 39)
# id(registro)
# 139954596718920
# id(registro_2)
# 139954596718600
# registro + registro_2
# ('Adriano', 47, 'Ros창ngela', 39)
# id(_)
# 139954597152552